"""empty message

Revision ID: 165ebf6e5e98
Revises: a2e1987cba9a
Create Date: 2018-06-05 01:32:22.939341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165ebf6e5e98'
down_revision = 'a2e1987cba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
