"""修改字段

Revision ID: 25c6a4db5101
Revises: 2354349311a5
Create Date: 2018-06-07 01:53:24.129567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25c6a4db5101'
down_revision = '2354349311a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.drop_column('user', 'loaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('loaction', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
