"""empty message

Revision ID: f7f27424037f
Revises: 165ebf6e5e98
Create Date: 2018-06-05 21:00:56.007068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f27424037f'
down_revision = '165ebf6e5e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('path', sa.String(length=128), nullable=True))
    op.add_column('posts', sa.Column('pid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'pid')
    op.drop_column('posts', 'path')
    # ### end Alembic commands ###
